TABLE_NAME_BOX = 'box'
TABLE_NAME_GOODS = 'goods'

COL_BOX_ID = COL_GOODS_ID = 'id'
COL_BOX_NAME = COL_GOODS_NAME = 'name'

# Status_code
SUCCESS_CODE = 200
SUCCESS_MESSAGE = 'Success'
ERROR_CODE = 400
ERROR_MESSAGE = 'Fail'
