TABLE_NAME_BOX = 'box'
TABLE_NAME_GOODS = 'goods'

COL_NAME_ID_BOX = COL_NAME_ID_GOODS = 'id'
COL_NAME_NAME_BOX = COL_NAME_NAME_GOODS = 'name'
COL_NAME_BOX_ID_GOODS = 'box_id'

# Status_code
SUCCESS_CODE = 200
SUCCESS_MESSAGE = 'Success'
ERROR_CODE = 400
ERROR_MESSAGE = 'Fail'
